/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tym_idea_jni_InputManagerJni */

#ifndef _Included_com_tym_idea_jni_InputManagerJni
#define _Included_com_tym_idea_jni_InputManagerJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tym_idea_jni_InputManagerJni
 * Method:    any2Chinese
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tym_idea_jni_InputManagerJni_any2Chinese
  (JNIEnv *, jobject);

/*
 * Class:     com_tym_idea_jni_InputManagerJni
 * Method:    any2Japanese
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tym_idea_jni_InputManagerJni_any2Japanese
  (JNIEnv *, jobject);

/*
 * Class:     com_tym_idea_jni_InputManagerJni
 * Method:    any2English
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tym_idea_jni_InputManagerJni_any2English
  (JNIEnv *, jobject);

/*
 * Class:     com_tym_idea_jni_InputManagerJni
 * Method:    state
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tym_idea_jni_InputManagerJni_state
  (JNIEnv *, jobject);

/*
 * Class:     com_tym_idea_jni_InputManagerJni
 * Method:    list
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tym_idea_jni_InputManagerJni_list
  (JNIEnv *, jobject);

/*
 * Class:     com_tym_idea_jni_InputManagerJni
 * Method:    remove
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tym_idea_jni_InputManagerJni_remove
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
